
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Entry textBoxForName;

	private global::Gtk.Button writeHelloButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.textBoxForName = new global::Gtk.Entry();
		this.textBoxForName.CanFocus = true;
		this.textBoxForName.Name = "textBoxForName";
		this.textBoxForName.IsEditable = true;
		this.textBoxForName.InvisibleChar = '●';
		this.fixed1.Add(this.textBoxForName);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.textBoxForName]));
		w1.X = 110;
		w1.Y = 41;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.writeHelloButton = new global::Gtk.Button();
		this.writeHelloButton.CanFocus = true;
		this.writeHelloButton.Name = "writeHelloButton";
		this.writeHelloButton.UseUnderline = true;
		this.writeHelloButton.Label = global::Mono.Unix.Catalog.GetString("Hello");
		this.fixed1.Add(this.writeHelloButton);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.writeHelloButton]));
		w2.X = 173;
		w2.Y = 93;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.writeHelloButton.Pressed += new global::System.EventHandler(this.OnWriteHelloButtonPressed);
	}
}
